worker_processes  auto;

events { worker_connections  1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  server {
    listen 80;
    server_name ${SERVER_NAME};

    # общие заголовки к бэкендам
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout  5s;
    proxy_send_timeout    30s;
    proxy_read_timeout    30s;

    # health
    location = /health {
      return 200 '{"status":"OK"}';
      add_header Content-Type application/json;
    }

    # Auth API
    location /api/auth/    { proxy_pass http://auth-service:8001; }

    # Content API
    location /api/content/ { proxy_pass http://content-api:8002; }

    # UGC API
    location /api/ugc/     { proxy_pass http://ugc-service:8003; }

    # Profile API (НОВОЕ)
    location /api/profile/ { proxy_pass http://profile-service:8000; }

    # Django admin
    location /admin/       { proxy_pass http://admin-panel:8004; }
  }
}
